### ISSUE TITLE
Back up pwrcoin-qt-x64-v3.0.0

### ISSUE THREAD

**Issue by Tuyenelec** [PWRcoin/PWRcoinClassic#26]
I have backup file "PWR 3_0.DAt" created by my wallet address. Because I lost that wallet. Now how can I back up my wallet from the "PWR 3_0.DAt" file. Help me please!

**Comment by PWRcoin** [comment]
Hi,
What do you mean with you lost that wallet ?

The way to restore a wallet.dat file is:
1 - stop wallet
2 - check %APPDATA%/Roaming/pwrcoin3/ doesnt already have a wallet.dat if it does rename it wallet.old
2 - copy your pwr_3_0.dat file to %APPDATA%/Roaming/pwrcoin3/wallet.dat
3 - start wallet

**Comment by Tuyenelec** [comment]
ThankS! I success!
