### ISSUE TITLE
кошелек офлайн

### ISSUE THREAD

**Issue by ekiboston** [PWRcoin/PWRcoinClassic#3]
почему кошелек pos показывает что нет активных соединений???

**Comment by PWRcoin** [comment]
Hi , i dont speak russian, i used google translate, 

добавьте следующие параметры в файл powercoin.conf
addnode=138.68.27.117:4504
addnode=154.16.7.192:4504
addnode=173.249.13.164:4504

**Comment by ekiboston** [comment]
Дорогой друг. К сожалению я не понял как это сделать ...если возможно сделайте видеообзор или более подробное описание... я думаю это поможет многим людям ...заранее большое спасибо.

**Comment by PWRcoin** [comment]
извините за мой бедный русский, создайте файл с именем powercoin.conf в той же папке, что и ваш wallet.dat

Затем поставьте строки addnode i, указанные в файле powercoin.conf.Затем перезапустите кошелек
