### ISSUE TITLE
Mercatox withdrawal

### ISSUE THREAD

**Issue by relapsing** [PWRcoin/PWRcoinClassic#30]
My Mercatox withdrawal is not showing up in PWR explorer, and Mercatox swears it was sent. Could you please let me know if the explorer is updated? Tx is attached.
![PWR](https://user-images.githubusercontent.com/32651759/61486991-cea81a80-a972-11e9-9b24-44b13db29859.JPG)

**Comment by ghobson2013** [comment]
The blockexplorer was out of sync, i am fixing it now. thanks for bringing this to my attention.

**Comment by ghobson2013** [comment]
if the last blocknr doesnt match the total blocks reported in the lower right corner it usually means the background sync job has stalled... ( it's a cron job ).
I will post here when the explorer is back in sync.

**Comment by ghobson2013** [comment]
The explorer is now in sync, please let me know if you see your TX now.

**Comment by relapsing** [comment]
I see it. Thank you.
    On Friday, July 19, 2019, 02:02:14 AM EDT, Gary Hobson <notifications@github.com> wrote:  
 
 
The explorer is now in sync, please let me know if you see your TX now.

**Comment by relapsing** [comment]
Ack, this tx isn't showing up either: 8c070421ea7ec71c7d3de258f1b5cfc5a30d33bf6a9447f41408277017f67b8f

**Comment by ghobson2013** [comment]
The block explorer stalled again, I am investigating...
re-syncing....

**Comment by ghobson2013** [comment]
I have applied the patch from https://github.com/iquidus/explorer/pull/67 , this should take care of this issue.

**Comment by DisasterFaster** [comment]
Mercatox and Crex24 exchanges are both tested and working properly so I am closing this issues. Many thanks to ghobson for pressuring Mercatox and getting a reasonably fast result!
