### ISSUE TITLE
Wallet Stuck on 75%

### ISSUE THREAD

**Issue by FelixMendoza** [PWRcoin/PWRcoinClassic#31]
Hi, I'm now having a different issue with my Mac wallet. I shut my wallet down for a fe weeks and now it stays stuck at 75.77% and I'm unable to see my balance. I also have a red "Out of Sync" message. Please see my screenshot. I'm also attaching the peers.dat and wallet.dat files. Any suggestions?
Thanks!
![Screen Shot 2019-08-12 at 7 47 04 PM](https://user-images.githubusercontent.com/106108/62905903-729aa100-bd3a-11e9-8bd2-19d44bfaa896.png)
[Archive.zip](https://github.com/PWRcoin/PWRcoin/files/3494754/Archive.zip)

**Comment by DisasterFaster** [comment]
Which MAC OS are you using? Can you check and see what your internet speed is and share that? Even though you are synchronizing it should still show the wallet balance. Have you tried deleting everything **EXCEPT** the wallet.dat and then reloading the blockchain using the bootstrap file? The bootstrap file is located here: https://github.com/PWRcoin/PWRcoin/releases/download/v3.1.0/bootstrap-30062019.tgz

**Comment by FelixMendoza** [comment]
Hi, thanks for the quick response. I have 39.22 MBPS download and 11.83 MBPS upload speeds.
I'll delete everything but the wallet.dat file and try reloading the blockchain using the bootstrap. I'll report back. Thanks again!

**Comment by FelixMendoza** [comment]
Also, I'm on MacOS Mojave 10.14.6

**Comment by DisasterFaster** [comment]
Yikes okay 39.22 MBPS is going to be a slow speed. The PWR Coin blockchain is lightning fast spitting out a block about every 30 seconds or so. Because of this you not only have to synchronize from the entry point of the bootstrap but also you must overtake the chain as it keeps moving forward. Once you are past the bootstrap and synchonizing and if you check your synch every 5 minutes can you verify that you are downloading fast enough that your block height is climbing faster than the chain is moving forward? In other words when checking and rechecking your synch every 5 minutes does the wallet show a lower and lower number of blocks left to synch?

**Comment by FelixMendoza** [comment]
OK, I'm not sure I understand exactly what you asked, but I took a screenshot of the progress exactly 5 minutes apart for about 20 minutes and I believe I'm downloading faster than the speed of the blockchain, if that's what you meant. LOL
Can you lease check the screenshots and let me know? One good thing is, at least I can now see my balance. One more question, what would the ideal speed be? I just checked my speed again and it clocked at 49.76 MBPS this time. Thanks again!

![Screen Shot 2019-08-12 at 11 57 57 PM](https://user-images.githubusercontent.com/106108/62914717-7c82cb00-bd5f-11e9-8adb-9fb2237ab692.png)
![Screen Shot 2019-08-13 at 12 04 48 AM](https://user-images.githubusercontent.com/106108/62914718-7c82cb00-bd5f-11e9-954e-54f04a7e23be.png)
![Screen Shot 2019-08-13 at 12 09 06 AM](https://user-images.githubusercontent.com/106108/62914720-7c82cb00-bd5f-11e9-9e9f-0456442cd493.png)
![Screen Shot 2019-08-13 at 12 09 09 AM](https://user-images.githubusercontent.com/106108/62914721-7c82cb00-bd5f-11e9-87ec-5761dd7c2c0e.png)
![Screen Shot 2019-08-13 at 12 14 54 AM](https://user-images.githubusercontent.com/106108/62914722-7c82cb00-bd5f-11e9-80a5-d1cd79f1e221.png)

**Comment by FelixMendoza** [comment]
OK, everything seems to be working fine. I'm staking again!
Thanks for your help!!

**Comment by DisasterFaster** [comment]
Awesome! I am closing this issue now and let the dev team know if you have any more problems.

**Comment by FelixMendoza** [comment]
Hi there, I'm having a similar issue again. This time it isn't stuck, but it does say it's offline.
I'm on v3.1.0.0 BTW
![pwr-wallet](https://user-images.githubusercontent.com/106108/73264675-4caa7100-41a1-11ea-9d73-cfe8c90de278.png)

**Comment by DisasterFaster** [comment]
You don't have any connections. Please go here: https://blockexplorer.pwr-coin.com/network and you can find active nodes and IP addresses.  Open your config file or if you don't have one create one and add some active nodes and reboot the wallet. You will need to name the file pwrcoin.conf and it should be located in the same folder where your wallet.dat and peers.dat files are. The format looks like the attached document but please add IP's that are currently showing in the block explorer.
[pwrcoin.conf.txt](https://github.com/PWRcoin/PWRcoin/files/4160866/pwrcoin.conf.txt)

**Comment by FelixMendoza** [comment]
Hi, OK so I now have active connections since 2 days ago, but the wallet isn't syncing. Do you have a bootstrap I can use so it can sync faster?
